[package]
name = "day05"
version = "0.1.0"
authors = ["Mark Thebridge <mark.thebridge@gmail.com>"]
edition = "2018"
publish = ["metaswitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
